apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/JustinBatchelor/multi-tenant-gitops-template/'
    targetRevision: HEAD
    path: clusters/dev2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true