{{- if .Values.acm.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  label:
    argocd.argoproj.io/managed-by: openshift-gitops
    openshift.io/cluster-monitoring: 'true'
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: advanced-cluster-management-group
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: {{ .Values.acm.subscription.channel | default "release-2.9" }}
  installPlanApproval: {{ .Values.acm.subscription.installPlanApproval | default "Automatic" }}
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.acm.subscription.startingCSV | default "advanced-cluster-management.v2.9.0" }}
---
{{- end }}