{{- if .Values.acs.enabled }}
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: central
  namespace: stackrox
spec: {}
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: {{ .Values.acs.deployment.securedCluster.name | default "svc-secured-cluster" }}
{{- end }}