{{- if .Values.quay.enabled }}
---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: svc-quay-registry
  namespace: quay-enterprise
spec:
  components:
    - kind: clair
      managed: {{ .Values.quay.deployment.clair.managed | default true }}
    - kind: redis
      managed: {{ .Values.quay.deployment.redis.managed | default true }}
    - kind: postgres
      managed: {{ .Values.quay.deployment.postgres.managed | default true }}
    - kind: objectstorage
      managed: {{ .Values.quay.deployment.objectstorage.managed | default true }}
    - kind: route
      managed: {{ .Values.quay.deployment.route.managed | default true }}
    - kind: mirror
      managed: {{ .Values.quay.deployment.mirror.managed | default true }}
    - kind: monitoring
      managed: {{ .Values.quay.deployment.monitoring.managed | default true }}
    - kind: tls
      managed: {{ .Values.quay.deployment.tls.managed | default true }}
---
{{- end }}