apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/JustinBatchelor/multi-tenant-gitops-template
    targetRevision: HEAD
    path: applications/operators/acm
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true