apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Red Hat Advanced Cluster Security Operator
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-security
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acs-operator-manager
  namespace: rhacs-operator
rules:
  - apiGroups: ["platform.stackrox.io"]
    resources: ["centrals", "scanners", "sensors"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-acs-manager-binding
  namespace: rhacs-operator
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: acs-operator-manager
  apiGroup: rbac.authorization.k8s.io

# ---
# apiVersion: platform.stackrox.io/v1alpha1
# kind: Central
# metadata:
#   name: central
#   namespace: stackrox
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec: {}
# ---
# apiVersion: platform.stackrox.io/v1alpha1
# kind: SecuredCluster
# metadata:
#   name: stackrox-secured-cluster-services
#   namespace: stackrox
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   clusterName: "svc-openshift-utl"