apiVersion: v1
kind: Namespace
metadata:
  name: acs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: acs-operator-group
  namespace: acs-operator
spec:
  targetNamespaces:
  - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acs-subscription
  namespace: acs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: advanced-cluster-security-for-kubernetes
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: advanced-cluster-security-for-kubernetes.vX.Y.Z # Replace with the specific version you need
---
### need to add the instance of the operator here