apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat Quay"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: quay-enterprise
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operatorgroup
  namespace: quay-enterprise
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-5"
spec:
  targetNamespaces:
  - quay-enterprise
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator-subscription
  namespace: openshift-operators
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-5"
spec:
  channel: stable-3.10 # Or another channel representing the latest version
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: quay-operator.v3.10.1 # Specify the desired starting CSV if needed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-registry-manager
  namespace: quay-enterprise
rules:
  - apiGroups: ["quay.redhat.com"] # The API group for QuayRegistry resources
    resources: ["quayregistries"]
    verbs: ["*"] # This grants all permissions. You can restrict this if needed.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-quay-registry-manager-binding
  namespace: quay-enterprise
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: quay-registry-manager
  apiGroup: rbac.authorization.k8s.io
---
### need to add the instance of the operator here
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quayregistry
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  components:
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
