apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat Quay"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: quay-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator-group
  namespace: quay-operator
spec:
  targetNamespaces:
    - quay-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
### need to add the instance of the operator here
