apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator-group
  namespace: quay-enterprise
spec:
  targetNamespaces:
  - quay-enterprise
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator-subscription
  namespace: quay-enterprise
spec:
  channel: stable
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: quay-operator.vX.Y.Z # Replace with the specific version you need
