apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat Quay"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: quay-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator-group
  namespace: quay-operator
  argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - quay-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator-subscription
  namespace: openshift-operators
  argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable-3.10 # Or another channel representing the latest version
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: quay-operator.v3.10.1 # Specify the desired starting CSV if needed

---
### need to add the instance of the operator here
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quayregistry
  namespace: quay-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  components:
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
